name: kubo
description: Food Planner

publish_to: "none"

version: 1.0.0+25

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  camera: ^0.9.4+19
  carousel_slider: ^4.0.0
  cross_file: ^0.3.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_beautiful_popup: ^1.7.0
  flutter_bloc: ^8.0.1
  flutter_colorpicker: ^1.0.3
  flutter_easyloading: ^3.0.3
  flutter_speed_dial: ^5.0.0+1
  get_it: ^7.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  http: ^0.13.4
  image_picker: ^0.8.4+10
  injectable: ^1.5.3
  intl: ^0.17.0
  path_provider: ^2.0.8
  pod_player: ^0.0.4
  skeletons: ^0.0.3
  syncfusion_flutter_calendar: ^19.4.40
  table_calendar: ^3.0.3
  timeline_tile: ^2.0.0
  animated_bottom_navigation_bar: ^0.3.2
  auto_size_text: ^3.0.0
  flutter_local_notifications: ^9.5.2
  rxdart: ^0.27.3
  flutter_native_timezone: ^2.0.0
  external_path: ^1.0.1
  mime: ^1.0.2
  image_downloader: ^0.31.0
  permission_handler: ^9.2.0
  flutter_countdown_timer: ^4.1.0
  dropdown_search: ^3.0.1
  art_sweetalert: ^0.0.5
  fraction: ^4.0.1
  url_launcher: ^6.1.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  mockito: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/carousel/
    - assets/images/calendar/

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf

    - family: Pushster
      fonts:
        - asset: assets/fonts/Pushster-Regular.ttf

    - family: Arvo
      fonts:
        - asset: assets/fonts/Arvo-Regular.ttf

    - family: Arvo Bold
      fonts:
        - asset: assets/fonts/Arvo-Bold.ttf

    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-SemiBold.ttf

    - family: JosefinSans Bold
      fonts:
        - asset: assets/fonts/JosefinSans-SemiBold.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: Montserrat Thin
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf

    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: Montserrat Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
